Denselight_EPMP/GnC/urls.py
from django.urls import path

from . import views
from .views import User_GnC, Manager_GnC,  Create_Departmental_Goals, Create_Competencies, Create_Departmental_Competencies

app_name = 'GnC'
urlpatterns = [
    path('user/', views.User_GnC, name = "User_GnC"),
    path('manager/', views.Manager_GnC, name = "Manager_GnC"),
    path('HR/', views.HR_GnC, name = "HR_GnC"),
    
    path('allusers/<int:pk>/create_departmental_goals/', views.Create_Departmental_Goals.as_view(), name = "Create_Manager_Goals"),
    path('allusers/<int:pk>/create_departmental_competencies/', views.Create_Departmental_Competencies.as_view(), name="Create_Manager_Competencies"),
    path('allusers/<int:pk>/create_goals/', views.Create_Goals.as_view(), name ="Create_User_Goals1"),
    path('allusers/<int:pk>/create_competencies/', views.Create_Competencies.as_view(), name = "Create_User_Competencies"),
    path('allusers/<int:pk>/create_KPI/', views.Create_KPI.as_view(), name = "Create_User_KPIs"),
    path('allusers/<int:pk>/UserGnC/Create_GoalsCom', views.Create_Goals_Comments.as_view(), name='Create_User_Goals_Comments'),
    path('allusers/<int:pk>/UserGnC/Create_CompetenciesCom', views.Create_Competencies_Comments.as_view(), name ='Create_User_Competencies_Comments'),

    path('allusers/<int:pk>/DepartmentG', views.Departmental_Goals_View.as_view(), name="Detail_Departmental_Goals"),
    path('allusers/<int:pk>/UserG', views.Goals_View.as_view(), name = "Detail_Goals"),
    path('allusers/<int:pk>/UserC', views.Competencies_View.as_view(), name="Detail_Competencies"),
    path('allusers/<int:pk>/UserGnC', views.Department_View.as_view(), name="Detail_Users"),
    path('allusers/<int:pk>/Departments', views.HRDepartment_view.as_view(), name="Detail_Departments"),

    path('allusers/<int:pk>/DeleteG', views.Goals_Delete.as_view(), name = "Delete_User_Goals"),
    path('allusers/<int:pk>/DeleteDepartmentalG', views.Departmental_Goals_Delete.as_view(), name ="Delete_Departmental_Goals"),
    path('allusers/<int:pk>/DeleteDepartmentalC', views.Departmental_Competencies_Delete.as_view(), name="Delete_Departmental_Competencies"),
    path('allusers/<int:pk>/DeleteC', views.Competencies_Delete.as_view(), name ="Delete_User_Competencies"),
    path('allusers/<int:pk>/DeleteKPI', views.KPI_Delete.as_view(), name="Delete_User_KPI"),

    path('allusers/<int:pk>/UpdateG', views.Update_Goals_User.as_view(), name ="Update_User_Goals1"),
    path('allusers/<int:pk>/UpdateDepartmentalG', views.Update_Departmental_Goals.as_view(), name ='Update_Departmental_Goals'),
    path('allusers/<int:pk>/UpdateDepartmentalC', views.Update_Departmental_Competencies.as_view(), name='Update_Departmental_Competencies'),
    path('allusers/<int:pk>/UpdateC', views.Update_Competencies_User.as_view(), name='Update_User_Competencies'),
    path('allusers/<int:pk>/UpdateKPI', views.Update_KPI.as_view(), name ='Update_KPI'),
    path('allusers/<int:pk>/UpdateKPI_POST', views.Update_KPI_POST.as_view(), name ='Update_KPI_POST'),
    path('allusers/<int:pk>/UpdateKPI_POST1', views.Update_KPI_POST1.as_view(), name ='Update_KPI_POST1'),
    path('allusers/<int:pk>/UpdateKPI_POST2', views.Update_KPI_POST2.as_view(), name ='Update_KPI_POST2'),
    path('allusers/<int:pk>/UpdateDepartment', views.Update_Departments.as_view(), name='Update_Department'),

    path('allusers/<int:pk>/CreatetheGoals', views.createGoals, name='Create_User_Goals'),
    path('allusers/<int:pk>/<int:mk>/UpdateG', views.updateGoals, name ="Update_User_Goals"),

    path('allusers/<int:pk>/GoalsImage', views.GoalsImage, name='Goals_Image'),
    path('allusers/<int:pk>/UploadGoalsImage', views.GoalsImageUpload, name='Goals_ImageUpload'),
]

EM/urls.py
from django.urls import path

from . import views

app_name = 'EM'
urlpatterns=[
    path('HR/', views.HR_EM, name = 'HR_EM'),
    path('HRM/', views.HRM_EM, name = 'HRM_EM'),

    path('HR/create_profiles/', views.Create_Profile.as_view(), name ='Create_Profile'),

    path('HR/<int:pk>/', views.Profile_View.as_view(), name ='Detail_Profile'),
    path('HR/<int:pk>/DeleteP', views.Delete_Profile.as_view(),name='Delete_Profile'),
    path('HR/<int:pk>/UpdateP', views.Update_Profile.as_view(), name ='Update_Profile')
]

GnC/urls.py
from django.urls import path

from . import views
from .views import User_GnC, Manager_GnC,  Create_Departmental_Goals, Create_Competencies, Create_Departmental_Competencies

app_name = 'GnC'
urlpatterns = [
    path('user/', views.User_GnC, name = "User_GnC"),
    path('manager/', views.Manager_GnC, name = "Manager_GnC"),
    path('HR/', views.HR_GnC, name = "HR_GnC"),

    path('allusers/<int:pk>/create_departmental_goals/', views.Create_Departmental_Goals.as_view(), name = "Create_Manager_Goals"),
    path('allusers/<int:pk>/create_departmental_competencies/', views.Create_Departmental_Competencies.as_view(), name="Create_Manager_Competencies"),
    path('allusers/<int:pk>/create_goals/', views.Create_Goals.as_view(), name ="Create_User_Goals1"),
    path('allusers/<int:pk>/create_competencies/', views.Create_Competencies.as_view(), name = "Create_User_Competencies"),
    path('allusers/<int:pk>/create_KPI/', views.Create_KPI.as_view(), name = "Create_User_KPIs"),
    path('allusers/<int:pk>/UserGnC/Create_GoalsCom', views.Create_Goals_Comments.as_view(), name='Create_User_Goals_Comments'),
    path('allusers/<int:pk>/UserGnC/Create_CompetenciesCom', views.Create_Competencies_Comments.as_view(), name ='Create_User_Competencies_Comments'),

    path('allusers/<int:pk>/DepartmentG', views.Departmental_Goals_View.as_view(), name="Detail_Departmental_Goals"),
    path('allusers/<int:pk>/UserG', views.Goals_View.as_view(), name = "Detail_Goals"),
    path('allusers/<int:pk>/UserC', views.Competencies_View.as_view(), name="Detail_Competencies"),
    path('allusers/<int:pk>/UserGnC', views.Department_View.as_view(), name="Detail_Users"),
    path('allusers/<int:pk>/Departments', views.HRDepartment_view.as_view(), name="Detail_Departments"),

    path('allusers/<int:pk>/DeleteG', views.Goals_Delete.as_view(), name = "Delete_User_Goals"),
    path('allusers/<int:pk>/DeleteDepartmentalG', views.Departmental_Goals_Delete.as_view(), name ="Delete_Departmental_Goals"),
    path('allusers/<int:pk>/DeleteDepartmentalC', views.Departmental_Competencies_Delete.as_view(), name="Delete_Departmental_Competencies"),
    path('allusers/<int:pk>/DeleteC', views.Competencies_Delete.as_view(), name ="Delete_User_Competencies"),
    path('allusers/<int:pk>/DeleteKPI', views.KPI_Delete.as_view(), name="Delete_User_KPI"),

    path('allusers/<int:pk>/UpdateG', views.Update_Goals_User.as_view(), name ="Update_User_Goals1"),
    path('allusers/<int:pk>/UpdateDepartmentalG', views.Update_Departmental_Goals.as_view(), name ='Update_Departmental_Goals'),
    path('allusers/<int:pk>/UpdateDepartmentalC', views.Update_Departmental_Competencies.as_view(), name='Update_Departmental_Competencies'),
    path('allusers/<int:pk>/UpdateC', views.Update_Competencies_User.as_view(), name='Update_User_Competencies'),
    path('allusers/<int:pk>/UpdateKPI', views.Update_KPI.as_view(), name ='Update_KPI'),
    path('allusers/<int:pk>/UpdateKPI_POST', views.Update_KPI_POST.as_view(), name ='Update_KPI_POST'),
    path('allusers/<int:pk>/UpdateKPI_POST1', views.Update_KPI_POST1.as_view(), name ='Update_KPI_POST1'),
    path('allusers/<int:pk>/UpdateKPI_POST2', views.Update_KPI_POST2.as_view(), name ='Update_KPI_POST2'),
    path('allusers/<int:pk>/UpdateDepartment', views.Update_Departments.as_view(), name='Update_Department'),

    path('allusers/<int:pk>/CreatetheGoals', views.createGoals, name='Create_User_Goals'),
    path('allusers/<int:pk>/<int:mk>/UpdateG', views.updateGoals, name ="Update_User_Goals"),

    path('allusers/<int:pk>/GoalsImage', views.GoalsImage, name='Goals_Image'),
    path('allusers/<int:pk>/UploadGoalsImage', views.GoalsImageUpload, name='Goals_ImageUpload'),

    path('allusers/<int:pk>/Create_Comment/', views.Create_Comment.as_view(), name = "Create_User_Comments"),
    path('allusers/<int:pk>/Update_Comment/', views.Update_Comment.as_view(), name ='Update_Comment'),
#     path('allusers/<int:pk>/Manager_Create_Comment/', views.Manager_Create_Comment.as_view(), name ='Manager_Create_Comment'),
#     path('allusers/<int:pk>/Manager_Update_Comment/', views.Manager_Update_Comment.as_view(), name ='Manager_Update_Comment'),
    path('allusers/<int:pk>/Mid_Yr_Create_Comment/', views.Mid_Yr_Create_Comment.as_view(), name = "Mid_Yr_Create_User_Comments"),
    path('allusers/<int:pk>/Mid_Yr_Update_Comment/', views.Mid_Yr_Update_Comment.as_view(), name ='Mid_Yr_Update_Comment'),

]

denselight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Denselight_EPMP/GnC/templates/GnC/GoalsImageView.html
 <h4>Metrics Evidence</h4><hr>
 <img src="{{goals.metrics_evidence.url}}">

Denselight_EPMP/GnC/templates/GnC/HuNet_DetailCompetencies.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%}
<!--To inform website version of HTML-->
<!DOCTYPE html>
<!--Inform website of language of HTML-->
<html lang="en">
<!--Header-->
<head>
      <!--Meta to improve SEO-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">

    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Competencies Detail{%endblock%}</title>
</head>
<body>
    <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
    {%block content%}

    <!--Things within double braces are object instances within a queryset, so in this case I am accessing object's employee name-->
    <p>Employee name: {{object.employee.name}}</p>
    <!--Accessing Competencies' category-->
    <p>Appraisal ID: {{object.competency_category.name}}</p>
    {% with comments_counter=object.competency_comment_set.all%}
    <p>Comments: {{comments_counter.count}}</p>
    {%endwith%}
    <!--Accessing Competencies' summary-->
    <table>
      <thead>
          <tr>
              <th scope="col">ID </th>
              <th scope="col">Category</th>
              <th scope="col">Summary</th>
              <th scope="col">Status</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>Competency {{object.id}}</td>
              <td>{{object.competency_category.name}}</td>
              <td>{{object.summary}}</td>
              <td>{{object.status}}</td>
          </tr>   
      </tbody>
  </table>

  <h4>Comments</h4>
  <a href="{%url 'GnC:Create_User_Competencies_Comments' object.id%}">Create Comments</a>
  <table>
      <thead>
          <tr>
              <th> </th>
              <th> </th>
              <th> </th>
              <th> </th>
              <th> </th>
              <th> </th>
              <th> </th>
          </tr>
      </thead>

      <tbody>
          {%for comments in object.competency_comment_set.all|dictsort:"created_on"%}
          {% if comments.created_by == comments.competency.employee %}
          <tr>
              <td rowspan="2" colspan="4">{{comments.created_by.name}}: {{comments.comments}}</td>
              <td colspan="3"></td>
          </tr>
          <tr>
              <td>{{comments.created_on}}</td>
              <td colspan="2"></td>
          </tr>
          {% else %}
          <tr>
              <td colspan="3"></td>
              <td rowspan="2" colspan="4">{{comments.created_by.name}}: {{comments.comments}}</td>
          </tr>
          <tr>
              <td colspan="2"></td>
              <td>{{comments.created_on}}</td>
          </tr>
          {%endif%}
          {%endfor%}
      </tbody>
  </table>

  {%endblock%}

Denselight_EPMP/GnC/templates/GnC/XHuNetHR_DetailDepartment.html
{%extends 'utilitypage.html'%}

Denselight_EPMP/GnC/templates/GnC/XHuNetM_GnC.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{% load static %}
<head>
    <!--HTML inheritance: overriding parent class title block(Django exclusive)-->
    <title>{%block title%}Goals and Competencies{%endblock%}</title>
</head>
<body>
    <!--Page wrapper bg-->
    <div class = "wrapper">
        <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
        {%block content%}

        <!--User vs Department tab-->
        <section class="main">
            <!--Tab section within goals-->
            <div class="tab_main">
                <button class="tablinks" onclick="openCity(event, 'self', 'General_Scope', 'tablinks')">User</button>
                <button class="tablinks" onclick="openCity(event, 'department', 'General_Scope', 'tablinks')">Department</button>
            </div>

            <!--User's Personal vs user's departmental goal tab-->
            <div class='General_Scope' id="self">
                <section class = "Goals">
                    <div class="tab_self">
                        <button class="tablinks1" onclick="openCity(event, 'goals_team', 'tabcontent_goals', 'tablinks1')">Departmental Goals and Competencies</button>
                        <button class="tablinks1" onclick="openCity(event, 'goals_self', 'tabcontent_goals', 'tablinks1')">Personal Goals and Competencies</button>
                    </div>

                    <!--**Dynamic routing to 'GnC/CreateDepartmentalGoals.html' template -->
                    <a href="{%url 'GnC:Create_Manager_Competencies'%}">Add Departmental Competencies</a>
                    <a href="{%url 'GnC:Create_Manager_Goals' %}">Add Departmental Goals</a>
                    <!--**Dynamic routing to 'GnC/CreateGoals.html' template -->
                    <a href="{%url 'GnC:Create_User_Goals' %}">Add User Goals</a>
                    <!--**Dynamic routing to 'GnC/CreateCompetencies.html' template -->
                    <a href="{% url 'GnC:Create_User_Competencies' %}">Add Competencies</a>

                    <!--Departmental goal table-->
                    <div id="goals_team" class="tabcontent_goals">
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Department</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Due date</th>
                                    <th scope="col" colspan=3>Progress</th>
                                </tr>
                            </thead>
                            <tbody>
                                {%for goals in departmental_goals_list%}
                                <tr>
                                    <td>{{goals.manager.name}}</td>
                                    <td>{{goals.summary}}</td>
                                    <td>{{goals.goal_category.name}}</td>
                                    <td>{{goals.due}}</td>
                                    <td>50%</td>
                                    <td><a href="{%url 'GnC:Update_Departmental_Goals' goals.id %}">+</a></td>
                                    <td><a href="{%url 'GnC:Delete_Departmental_Goals' goals.id %}">-</a></td>
                                    <td><a href ="{% url 'GnC:Detail_Departmental_Goals' goals.id %}">Details</a></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>

                        <!--Competency table (no tabs)-->
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Department</th>
                                    <th scope="col">Competencies</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Due date</th>
                                    <th scope="col" colspan="2">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                {%for competencies in departmental_competencies_list%}
                                <tr>
                                    <td>{{competencies.department}}</td>
                                    <td>{{competencies.summary}}</td>
                                    <td>{{competencies.competency_category}}</td>
                                    <td><a href = "{% url 'GnC:Detail_Competencies' competencies.id %}">Details</a></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>

                    <!--User goal table-->
                    <div id="goals_self" class="tabcontent_goals">
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Description</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Due date</th>
                                    <th scope="col">Progress</th>
                                    <th scope="col" colspan="4">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                {%for goals in goals_list%}
                                <tr>
                                    <td>{{goals.summary}}</td>
                                    <td>{{goals.goal_category.name}}</td>
                                    <td>{{goals.due}}</td>
                                    <td>75%</td>
                                    <td><a href="{%url 'GnC:Create_User_KPIs' goals.id %}">KPI</a></td>
                                    <td><a href="{% url 'GnC:Update_User_Goals' goals.id %}">+</a></td>
                                    <td><a href = "{% url 'GnC:Delete_User_Goals' goals.id %}">-</a></td>
                                    <td><a href = "{% url 'GnC:Detail_Goals' goals.id %}">Details</a></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>

                        <!--Competency table (no tabs)-->
                        <table>
                            <tr>
                                <th scope="col">Competencies</th>
                                <th scope="col">Category</th>
                                <th scope="col">Due date</th>
                                <th scope="col" colspan="2">Action</th>
                            </tr>

                            {%for competencies in competencies_list%}
                            <tr>
                                <td>{{competencies.summary}}</td>
                                <td>{{competencies.competency_category.name}}</td>
                                <td>{{competencies.due}}</td>
                                <td><a href="{% url 'GnC:Update_Competencies' competencies.id %}">+</a></td>
                                <td><a href = "{% url 'GnC:Delete_User_Competencies' competencies.id %}">-</a></td>
                                <td><a href = "{% url 'GnC:Detail_Competencies' competencies.id %}">Details</a></td>
                            </tr>
                            {%endfor%}
                        </table>
                    </div>
                </section>

            </div>

            <hr><!--Horizontal rule-->

            <!--Employee Departmental Tab & table-->
            <div class="General_Scope" id="department">
                <section class = "Goals_search team_view">

                    <!--Search form with submit button-->
                    <form class="example">
                        <input type="text" placeholder="Search.." name="search">
                        <button type="submit"><i class="fa fa-search">Submit</i></button>
                    </form>

                    <table>
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th 
                                scope="col">Department</th>
                                <th scope="col">Email</th>
                                <th scope="col">Goal count</th>
                                <th scope="col">Competencies count</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            {%for profile in department_detailed_view%}
                            <tr>
                                <td>{{profile.name}}</td>
                                <td>{%for x in profile.department.all%}:{{x.name}}: {%endfor%}</td>
                                <td>{{profile.email}}</td>
                                <td>{{profile.goals_set.all.count}}</td>
                                <td>{%with competency_count=profile.competencies_set.all%}{{competency_count|length}}{%endwith%}</td>
                                <td>Locked</td>
                                <td><a href = "{% url 'GnC:Detail_Users' profile.id %}">Details</a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </section>
            </div>

        </section>
        {%endblock%}
    </div>
</body>

Denselight_EPMP/GnC/templates/GnC/XHuNet_GnC.html
<!--Inherit HTML from parent class 'utiltiypage'-->
{%extends 'utilitypage.html'%}

<!--Load static is to load static files (HTML/CSS/Js)-->
{%load static%} 
<head>
<!--HTML inheritance: overriding parent class title block(Django exclusive)-->
<title>{%block title%} Goals and Competencies{%endblock%}</title>    <!--bootstrap and jquery-->
<script src="js/jquery-3.4.1.min.js"></script>
<script src="js/custom.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!--font-->
<link href="https://fonts.googleapis.com/css2?family=Hind:wght@600&display=swap" rel="stylesheet"> <!--hind-->
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet"> <!--open sans-->


</head>

<body>
    <div class = "wrapper">
        <!--HTML inheritance: overriding parent class content block(Django exclusive)-->
        {%block content%}
        <section class = "Goals">
            <!--Tab section within goals-->
            <div class="tab">
                <button class="tablinks" onclick="openCity(event, 'goals_team', 'tabcontent_goals', 'tablinks')">Departmental Goals</button>
                <button class="tablinks" onclick="openCity(event, 'goals_self', 'tabcontent_goals', 'tablinks')">Personal goals</button>
            </div>

            <!--**Dynamic routing to 'GnC:CreateGoals.html' template -->
            <a href="{%url 'GnC:Create_User_Goals'%}">Add Goals</a> 
            <!--**Dynamic routing to 'GnC:CreateCompetencies.html' template -->
            <a href="{%url 'GnC:Create_User_Competencies' %}">Add Competencies</a>

            <!--Departmental Goals table-->
            <div id="goals_team" class="tabcontent_goals">
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Description</th>
                            <th scope="col">Category</th>
                            <th scope="col">Due date</th>
                            <th scope="col">Progress</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for goals in departmental_goals_list %}
                        <tr>
                            <td>{{goals.summary}}</td>
                            <td>{{goals.goal_category.name}}</td>
                            <td>{{goals.due}}</td>
                            <td>50%</td>
                            <td><a href = "{%url 'GnC:Detail_Departmental_Goals' goals.id %}">Details</a></td>
                        </tr>
                        {%endfor%}
                    </tbody>
                    
                </table>
                <!--<div id="accordion">
                    <h3>Section 1</h3>
                    <div>
                      <p>
                      Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
                      ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
                      amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
                      odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
                      </p>
                </div>-->
            </div>

            <!--User goals table-->
            <div id="goals_self" class="tabcontent_goals">
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Description</th>
                            <th scope="col">Category</th>
                            <th scope="col">Due date</th>
                            <th scope="col">Progress</th>
                            <th scope="col" colspan="3">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for goals in goals_list %}
                        <tr>
                            <td>{{goals.summary}}</td>
                            <td>{{goals.goal_category.name}}</td>
                            <td>{{goals.due}}</td>
                            <td>70%</td>
                            <!--**Dynamic routing to 'GnC:CreateKPIs.html' template -->    
                            {% if goals.status == 'Employee' %}        
                            <td><a href="{%url 'GnC:Create_User_KPIs' goals.id %}">Add KPIs</a></td>
                            <td><a href="{% url 'GnC:Update_User_Goals' goals.id %}">Edit</a></td>
                            <td><a href="{% url 'GnC:Delete_User_Goals' goals.id %}">Delete</a></td>
                            {% elif goals.status == 'Manager' %}
                            <td><a href="{%url 'GnC:Create_User_KPIs' goals.id %}">Add KPIs</a></td>
                            <td></td>
                            <td><a href="{% url 'GnC:Delete_User_Goals' goals.id %}">Delete</a></td>
                            {% else %}
                            <td></td>
                            <td></td>
                            <td></td>
                            {%endif%}
                            <td><a href = "{%url 'GnC:Detail_Goals' goals.id %}">Details</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>

        <hr>

        <!--User competencies table-->
        <section class="Competencies">
            <div id="competencies_self">
                <table>
                    <tr>
                        <th scope="col">Competencies</th>
                        <th scope="col">Category</th>
                        <th scope="col" colspan="3">Action</th>
                    </tr>

                    {% for competencies in competencies_list %}
                    <tr>
                        <td>{{competencies.summary}}</td>
                        <td>{{competencies.competency_category.name}}</td>
                        {% if competencies.status == 'Employee' %}
                        <td><a href="{% url 'GnC:Update_User_Competencies' competencies.id %}">Edit</a></td>
                        <td><a href = "{%url 'GnC:Delete_User_Competencies' competencies.id %}">Delete</a></td>
                        {% elif competencies.status == 'Manager' %}
                        <td></td>
                        <td><a href = "{%url 'GnC:Delete_User_Competencies' competencies.id %}">Delete</a></td>
                        {% else %}
                        <td></td>
                        <td></td>
                        {% endif %}
                        <td><a href = "{%url 'GnC:Detail_Competencies' competencies.id %}">Details</a></td>
                    </tr>
                    {%endfor%}
                </table>
            </div>
        </section>
        {%endblock%}
    </div>
</body>