Appraisals/urls.py
from django.urls import path

from . import views

app_name = 'Appraisals'
urlpatterns = [

    path('allusers/Create_AppraisalCategory', views.Create_Appraisal_Category.as_view(), name="Create_Appraisal_Category"),
    path('allusers/<int:pk>/Create_User_Appraisal_List', views.Create_User_Appraisal_List.as_view(), name="Create_User_Appraisal_List"),

    path('allusers/<int:pk>/UpdateOverallAppraisal',views.update_Overall_Appraisal, name="Update_Overall_Appraisal"),
    #path('allusers/<int:pk>/<int:mk>/Update', views.UpdateAppraisal, name="Update_Appraisal"),

    path('allusers/<int:pk>/OverallAppraisal', views.Detail_Overall_Appraisal.as_view(), name="Detail_Overall_Appraisal"),
    path('allusers/<int:pk>/<int:mk>/UserAppraisal/', views.Detail_User_Appraisal_List.as_view(), name="Detail_User_Appraisal"),
    path('allusers/<int:pk>/<int:mk>/HRUserAppraisal/', views.Detail_HRUser_Appraisal_List.as_view(), name="HRDetail_User_Appraisal"),

    path('allusers/<int:pk>/DeleteUserAppraisal', views.Delete_User_Appraisal_List.as_view(), name="Delete_User_Appraisal"),
    path('allusers/<int:pk>/DeleteOverallAppraisal', views.Delete_Overall_Appraisal.as_view(), name='Delete_Overall_Appraisal'),

    path('allusers/<int:pk>/EtM/AppraisalFlow', views.EtM_User_Appraisal_List.as_view(), name='EtM_Appraisal'),
    path('allusers/<int:pk>/MtE/AppraisalFlow', views.MtE_User_Appraisal_List.as_view(), name='MtE_Appraisal'),
    path('allusers/<int:pk>/MtS1BE', views.MtS1BE_User_Appraisal_List.as_view(), name='MtS1BE_Appraisal'),

    path('allusers/<int:pk>/S1BEtS1BM', views.S1BEtS1BM_User_Appraisal_List.as_view(), name='S1BEtS1BM_Appraisal'),
    path('allusers/<int:pk>/S1BMtS1BR', views.S1BMtS1BR_User_Appraisal_List.as_view(), name='S1BMtS1BR_Appraisal'),
    path('allusers/<int:pk>/S1BRtS1BM', views.S1BRtS1BM_User_Appraisal_List.as_view(), name='S1BRtS1BM_Appraisal'),
    path('allusers/<int:pk>/S1BMtS2E', views.S1BMtS2E_User_Appraisal_List.as_view(), name='S1BMtS2E_Appraisal'),

    path('allusers/<int:pk>/S2EtS2M', views.S2EtS2M_User_Appraisal_List.as_view(), name='S2EtS2M_Appraisal'),
    path('allusers/<int:pk>/S2MtApp', views.S2MtApp_User_Appraisal_List.as_view(), name='S2MtApp_Appraisal'),
    path('allusers/<int:pk>/ApptS2M', views.ApptS2M_User_Appraisal_List.as_view(), name='ApptS2M_Appraisal'),
    path('allusers/<int:pk>/S2MtAppR', views.S2MtAppR_User_Appraisal_List.as_view(), name='S2MtAppR_Appraisal'),
   # path('allusers/<int:pk>/<int:mk>/Update1', views.updateAppraisal2.as_view(), name="Update_Appraisal1")
    path('allusers/<int:pk>/UpdateMidYear/UpdateG/', views.UpdateMidAppraisalG, name="Update_MIDAppraisalG"),
    path('allM/<int:pk>/UpdateMidYear/UpdateG/', views.UpdateMidAppraisalG_M, name="Update_MIDAppraisalG_M"),

    path('allusers/<int:pk>/Update/UpdateS/UpdateC/UpdateG/', views.UpdateAppraisalG, name="Update_AppraisalG"),
    path('allusers/<int:pk>/Update/UpdateS/UpdateC/', views.UpdateAppraisalC, name='Update_AppraisalC'),
    path('allusers/<int:pk>/Update/UpdateS/', views.UpdateAppraisalS, name='Update_AppraisalS'),
    path('allusers/<int:pk>/Update/Career', views.createCareerDiscussion, name='Update_AppraisalCareer'),
    path('allusers/<int:pk>/Update/', views.Update_Appraisal, name='Update_Appraisal'),

    path('allM/<int:pk>/Update/UpdateS/UpdateC/UpdateG/', views.UpdateAppraisalG_M, name="Update_AppraisalG_M"),
    path('allM/<int:pk>/Update/UpdateS/UpdateC/', views.UpdateAppraisalC_M, name='Update_AppraisalC_M'),
    path('allM/<int:pk>/Update/UpdateS/', views.UpdateAppraisalS_M, name='Update_AppraisalS_M'),
    path('allM/<int:pk>/Update/Career', views.UpdateAppraisalCareer_M, name='Update_AppraisalCareer_M'),
    path('allM/<int:pk>/Update/', views.Update_Appraisal_M, name='Update_Appraisal_M'),

    path('allHR/<int:pk>/Update/UpdateS/UpdateC/UpdateG/', views.UpdateAppraisalG_B, name="Update_AppraisalG_B"),
    path('allHR/<int:pk>/Update/UpdateS/UpdateC/', views.UpdateAppraisalC_B, name='Update_AppraisalC_B'),
    path('allHR/<int:pk>/Update/UpdateS/', views.UpdateAppraisalS_B, name='Update_AppraisalS_B'),
    path('allHR/<int:pk>/Update/Career', views.UpdateAppraisalCareer_B, name='Update_AppraisalCareer_B'),
    path('allHR/<int:pk>/Update/', views.Update_Appraisal_B, name='Update_Appraisal_B'),


    #Checkbox User Appraisals
    path('allHR/<int:pk>/AddUserAppraisal_Indiv', views.Add_User_Appraisal_Indiv, name='Invite_Indiv_User_Appraisal'),
    path('allHR/<int:pk>/AddUserAppraisal_Dept', views.Add_User_Appraisal_Dept, name='Invite_Dept_User_Appraisal'),
    path('allHR/<int:pk>/AddUserAppraisal_Company', views.Add_User_Appraisal_Company, name='Invite_Company_User_Appraisal'),

    path('allusers/Create_Peer_Appraisal', views.Create_Peer_Appraisal, name="Create_Peer_Appraisal"),
    path('allusers/<int:pk>/Update_Peer_Appraisal', views.Update_Peer_Appraisal, name="Update_Peer_Appraisal"),
    
    # path('allusers/<int:pk>/Add_peerAppraisalQuestions', views.Add_peerAppraisalQn, name='Add_PeerAppraisalQn'),

    path('allusers/Create_OverallAppraisal/Stage1', views.create_Overall_Appraisal_Stage1, name="Create_Overall_Appraisal1"),
    path('allusers/<int:pk>/Create_OverallAppraisal/Stage3', views.create_Overall_Appraisal_Stage3, name="Create_Overall_Appraisal_Stage3"),
    path('allusers/<int:pk>/Create_OverallAppraisal/Stage4', views.create_Overall_Appraisal_Stage4, name="Create_Overall_Appraisal_Stage4"),

    path('allusers/<int:pk>/<int:mk>/<int:dk>/PersonalRecord/OverallAppraisal/Detail', views.PersonalAppraisalReport, name="Detail_PersonalRecord_OverallApp"),


    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/FAR', views.Comp_FinalAppReport, name='Comp_FAReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportFAR', views.export_FinalAppraisalReport, name='export_FAReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/FPR', views.Comp_FinalPayoutReport, name='Comp_FPReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportFPR', views.export_FinalPayoutReport, name='export_FPReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/IRR', views.Comp_IncremRecommReport, name='Comp_IRReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportIRR', views.export_IncremRecommReport, name='export_IRReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/TRR', views.Comp_TrainingRecommReport, name='Comp_TRReport'),
    path('allusers/<int:pk>/CompanyRecord/ExportTRR', views.export_TrainingRecommReport, name='export_TRReport'),

    path('allusers/<int:pk>/CompanyRecord/OverallAppraisal/CR', views.Comp_CalibrationReport, name='Comp_CPReport'),
]

EM/urls.py
from django.urls import path

from . import views

app_name = 'EM'
urlpatterns=[
    path('HR/', views.HR_EM, name = 'HR_EM'),
    path('HRM/', views.HRM_EM, name = 'HRM_EM'),

    path('HR/create_profiles/', views.Create_Profile.as_view(), name ='Create_Profile'),

    path('HR/<int:pk>/', views.Profile_View.as_view(), name ='Detail_Profile'),
    path('HR/<int:pk>/DeleteP', views.Delete_Profile.as_view(),name='Delete_Profile'),
    path('HR/<int:pk>/UpdateP', views.Update_Profile.as_view(), name ='Update_Profile')
]

denselight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login2.urls')),
    path('Trainings/', include('Trainings.urls')),
    path('EM/', include('EM.urls')),
    path('Ticketing/', include('Ticketing.urls')),
    path('GnC/', include('GnC.urls')),
    path('Appraisals/', include('Appraisals.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path,include
from rest_framework import routers
from .api import LoginViewSet
# from django.contrib.auth import view as auth_views

from .views import (login_page)

router = routers.DefaultRouter()
router.register('api/', LoginViewSet, 'Loggins')

app_name = ''

urlpatterns = [
    path('', login_page, name ="login-page")
    # path('reset_password/', auth_views.PasswordResetView.as_view(), name="rest_password")
    # path('',include(django.contrib.auth.views))
]

login2/urls.py
from django.urls import path
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from . import views

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('userhome/', views.user_dashboard, name='user_homepage'),
    path('managerhome/', views.manager_dashboard, name='manager_homepage'),
    path('hrhome/', views.HR_dashboard, name='hr_homepage'),
    path('hrmanagerhome/', views.HRmanager_dashboard, name='hrmanager_homepage'),
    # path('Change_Password/'), views.change_password, name='passwordchangeview'),

    path('profile/Create', views.Create_Profile, name='Create_Profile'),
    path('profile/Bulkcreate', views.Profile_Upload, name='BulkCreate_Profile'),

    path('profile/all/<int:pk>/Update', views.Update_Profile, name='UpdateProfilepage'),
    path('profile/HRM/<int:pk>/Update', views.Update_Profile_HR, name='HRM_UpdateProfilepage'),

    path('profile/all/<int:pk>', views.Detail_Profile, name='Detail_Profile'),
    path('profile/HRM/<int:pk>', views.Detail_Profile_HR, name='Detail_Profile_HR'),

    path('profile/all/<int:pk>/CreateQualifications', views.Create_Qualifications.as_view(),
         name='Create_Qualifications'),
    path('profile/all/<int:pk>/<int:mk>/DeleteQualifications', views.Delete_Qualifications.as_view(),
         name='Delete_Qualifications'),

    path('profile/HRM/<int:pk>/CreateQualifications', views.Create_Qualifications_HR.as_view(),
         name='HRM_Create_Qualifications'),
    path('profile/HRM/<int:pk>/<int:mk>/DeleteQualifications', views.Delete_Qualifications_HR.as_view(),
         name='HRM_Delete_Qualifications'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="login2/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="login2/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="login2/password_reset_form.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="login2/password_reset_done.html"),
         name="password_reset_complete"),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name="login2/password_change_form.html", success_url='login2/password_change_done'),
         name = "password_change"),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="login2/password_change_done.html"),
         name="password_change_done"),
    ]

Denselight_EPMP/login/models.py
from django.db import models

class Login(models.Model):
    username = models.CharField(max_length = 100, blank = False, unique = True, null = False)
    password = models.CharField(max_length = 100, blank = False, null = False)

Denselight_EPMP/login2/models.py
from django.contrib.auth.models import User

def get_first_name(self):
    return self.username + ": " + self.email

User.add_to_class("__str__", get_first_name)

login/models.py
from django.db import models

class Login(models.Model):
    username = models.CharField(max_length = 100, blank = False, unique = True, null = False)
    password = models.CharField(max_length = 100, blank = False, null = False)

login2/models.py
from django.contrib.auth.models import User


def get_first_name(self):
    return self.username + ": " + self.email


User.add_to_class("__str__", get_first_name)

Denselight_EPMP/login/forms.py
from django import forms
from .models import Login

class LoginForm(forms.ModelForm):
    username = forms.CharField      (max_length = 100, 
    required = True)
    password = forms.CharField(max_length = 100, required = True)
    
    class meta:
        model = Login
        field = [
            'username',
            'password'
        ]

login/forms.py
from django import forms
from .models import Login

class LoginForm(forms.ModelForm):
    username = forms.CharField      (max_length = 100, 
    required = True)
    password = forms.CharField(max_length = 100, required = True)
    
    class meta:
        model = Login
        field = [
            'username',
            'password'
        ]

Denselight_EPMP/login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth

from .forms import LoginForm


def login_page(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect("")

        else:
            messages.info(request, 'Invalid username / password')
            return redirect("")

    return render(request, 'login/login.html')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('register')

            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('register')

            else:
                user = User.objects.create_user(username=username, password=password1, email=email,
                                                first_name=first_name, last_name=last_name)
                user.save()
                print('user created')
                return redirect('login')
        else:
            messages.info(request, 'Unmatched Password')
            return redirect('register')
        return redirect('/')

    else:
        return render(request, 'register.html')  # Get request, submitting info = post request

login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth

from .forms import LoginForm


def login_page(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect("")

        else:
            messages.info(request, 'Invalid username / password')
            return redirect("")

    return render(request, 'login/login.html')


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('register')

            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('register')

            else:
                user = User.objects.create_user(username=username, password=password1, email=email,
                                                first_name=first_name, last_name=last_name)
                user.save()
                print('user created')
                return redirect('login')
        else:
            messages.info(request, 'Unmatched Password')
            return redirect('register')
        return redirect('/')

    else:
        return render(request, 'register.html')  # Get request, submitting info = post request

login2/templates/login2/All_DetailProfile.html
{%extends 'homepage.html'%}
{% load thumbnail %}
<head>
    {%block title%}Employee Profile{%endblock%}

    {%block script1%}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script>
        function toggleFunction() {
          var x = document.getElementById("pw");
          var y = document.getElementById("pw-dots");
          if (x.style.display === "none") {
            x.style.display = "block";
            y.style.display = "none";
            document.getElementById("toggle-pw").innerHTML = "Hide Password";
          } else {
            x.style.display = "none";
            y.style.display = "block";
            document.getElementById("toggle-pw").innerHTML = "Show Password";
          }
        }
    </script>

    <style>
        .card {
            border: 0.2px solid #eee;
        }

        .displaypic {
            font-size: 140px !important;
            color: #eee; 
        }

        .display-card .card-header {
            background: rgb(138, 179, 180);
        }

        .display-card .card-body {
            font-size: 18px;
        }

        .display-card .card-body p{
            color: rgb(80, 131, 133);
        }

        .name {
            text-transform: uppercase;
            font-weight: 600;
            font-size: 20px;
            color: black !important;
        }

        .sec-info-card .table th, .sec-info-card table td,
        .EM-card .table th, .EM-card table td {
            border: none;
        }




    </style>
    {%endblock%}

</head>

<body>
    {%block content%}
    <div class = "container">
        <div class = "row col-12 justify-content-end" style = "margin:0; padding:0;">
            <a href="{%url 'UpdateProfilepage' object.id%}"><button class = "btn btn-info" type = "button">Update Profile</button></a>
        </div>

        <br>

        <div class = "row">
            <div class = "col-5">
                <div class = "card shadow h-100 text-center display-card">
                    <div class = "card-header">
                        {%if object.profile_Picture%}
                        <img src="{{ object.profile_Picture.url }}" style="width:140px; height:140px; border-radius:50%">
                        {%else%}
                        <i class="displaypic fa fa-user-circle-o" aria-hidden="true"></i>
                        {%endif%}
                    </div>

                    <div class = "card-body">
                        <p class = "name">{{object.name}}</p>                
                        <p>Employee ID: {{object.employee_ID}}{%if not object.employee_ID%}<strong>---</strong>{%endif%}</p>
                        <p>NRIC/FIN: {{object.nric}}{%if object.employee_ID == ' '%}<strong>---</strong>{%endif%}</p>
                        <p><i class="fa fa-user-o" aria-hidden="true"></i> {{object.gender}}</p>
                        <p><i class="fa fa-envelope-o" aria-hidden="true"></i> {{object.email}}</p>
                        <p><i class="fa fa-phone" aria-hidden="true"></i> {{object.phone}}</p>
                        
                        <hr>

                        <div class = "text-left">
                            <p>Username: {{object.user.username}}</p>
                            <p>Password: 
                                <span id = "pw-dots" style = "display: block;">••••••••••</span>
                                <span id = "pw" style = "display: none;">{{object.user.password}}</span>
                            </p>
                            <button id = "toggle-pw" onclick = "toggleFunction()" class = "btn btn-secondary" type = "button">Show Password</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class = "col-7">
                <div class = "card EM-card">
                    <div class = "card-header">
                        <h4>Employment Details</h4>
                    </div>

                    <div class = "card-body">
                        <table class = "table" style="width:100%">
                            <tr>
                              <th>Department</th>
                              <th>:</th>
                              <td>{{object.department.name}}</td>
                            </tr>
                            <tr>
                                <th>Section</th>
                                <th>:</th>
                                <td>{{object.division_Centre}}</td>
                            </tr>
                            <tr>
                              <th>Date-Of-Hire</th>
                              <th>:</th>
                              <td>{{object.date_Of_Hire}}</td>
                            </tr>
                            <tr>
                              <th>Job Title</th>
                              <th>:</th>
                              <td>{{object.employment_Type}} {{object.job_Title}}</td>
                            </tr>
                            
                            <tr>
                                <th>Direct Manager/Supervisor</th>
                                <th>:</th>
                                {%if object.first_Reporting_Manager == null%}
                                <td><strong>---</strong></td>                            
                                {%else%}
                                <td>{{object.first_Reporting_Manager}}</td>                           
                                {%endif%}
                            </tr>
                            <tr>
                                <th>HOD</th>
                                <th>:</th>
                                <td>{{object.second_Reporting_Manager}}</td>
                            </tr>
                            
                        </table>
                    </div>
                </div>
                
                <br>

                <div class = "card">
                    <div class = "card-header">
                        <h4>Skills</h4>
                        
                    </div>
                    
                    <div class = "card-body">
                        <table>
                            <th style='width:33%'></th>
                            <th style='width:33%'></th>
                            <th style='width:33%'></th>
                        </table>
                        <tr>
                            {%for skills in profile_skills_database1%}
                            <td>{{skills.skill_category.name}}</td>
                            {%endfor%}
                        </tr>
                        <tr>
                            {%for skills in profile_skills_database2%}
                            <td>{{skills.skill_category.name}}</td>
                            {%endfor%}
                        </tr>
                        <tr>
                            {%if object.skill1 %}
                            <td>{{object.skill1}}</td>
                            {%endif%}
                            {%if object.skill2 %}
                            <td>{{object.skill2}}</td>
                            {%endif%}
                            {%if object.skill3 %}
                            <td>{{object.skill3}}</td>
                            {%endif%}
                        </tr>
                    </div>
                </div>

            </div>
        </div>

        <br>

        <div class = "row">
            <div class = "col-5">
                <div class = "card sec-info-card">
                    <div class = "card-header">
                        <h4>Secondary Information</h4>
                    </div>

                    <div class = "card-body">
                        <table class = "table" style="width:100%">
                            <tr>
                              <th>Address 1</th>
                              <th>:</th>
                              <td>{{object.address_1}}</td>
                            </tr>
                            <tr>
                              <th>Address 2</th>
                              <th>:</th>
                              {%if object.address_2 == null or object.address_2 == ''%}
                              <td><strong>---</strong></td>
                              {%else%}
                              <td>{{object.address_2}}</td>
                              {%endif%}
                            </tr>
                            <tr>
                                <th>Date of Passport Expiry</th>
                                <th>:</th>
                                <td>{{object.date_Of_Passport_Expiry}}</td>
                            </tr>
                            <tr>
                                <th>Citizenship Status</th>
                                <th>:</th>
                                <td>{{object.citizenship_Status}}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            
            <div class = "col-7">
                <div class = "card">
                    <div class = "card-header">
                        <table><td style="width:100%;"><h4>Education Details</h4> </td> <td><div class = "row col-12 justify-content-end" style = "margin:0; padding:0;"><a href="{%url 'Create_Qualifications' object.id%}"><button class = "btn btn-info" type = "button">Add</button></a></div></td></table>
                    </div>
                    
                    <div class = "card-body py-0">
                        <table class = "table">
                            <thead>
                                <th style = "border-top: none;">Institution</th>
                                <th style = "border-top: none;">Qualifications Attained</th>
                                <th style = "border-top: none;">Graduation Year</th>
                                <th style = "border-top: none;"></th>
                            </thead>

                            <tbody>
                                {%if object.qualification_set.count == False %}
                                <tr>              
                                    <td colspan = "4"> User has not filled educational details. </td> 
                                </tr>
                                {%else%}
                                {% for qualifications in qualifications_database%}
                                <tr>
                                    <td>{{qualifications.institution}}{%if qualifications.institution == ''%}<strong>---</strong>{%endif%}</td>
                                    <td> {{qualifications.name}}</td>
                                    <td>{{qualifications.graduation_year}}{%if qualifications.graduation_year == ''%}<strong>---</strong>{%endif%}</td>
                                    <td><a href="{% url 'Delete_Qualifications' object.id qualifications.id%}">Delete</a></td>
                                </tr>
                                {%endfor%}
                                {%endif%}
                            </tbody>
                        </table>

                        <p></p> 
                    </div>
                </div>

                <br>
                <div class = "card training-records-card">
                    <div class = "card-header">
                        <h4>Training Records</h4>
                    </div>

                    <div class = "card-body py-0">
                        <table class = "table">
                            <thead>
                                <th style = "border-top: none;">Training Course</th>
                                <th style = "border-top: none;">Skill Category</th>
                            </thead>

                            <tbody> 
                                <tr>
                                    <td>Feature coming soon</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>

                <br>

                <div class = "card past-appraisal-records-card">
                    <div class = "card-header">
                        <h4>Past Appraisal Records</h4>
                    </div>
                    
                    <div class = "card-body py-0">
                        <table class = "table">
                            <thead>
                                <th style = "border-top: none;">Appraisal Name</th>
                            </thead>

                            <tbody>
                                {%if comp_overall_appraisal_database.count == False%}
                                <tr>
                                    <td>There are no past appraisal records.</td>
                                </tr>
                                {%endif%}
                                {%for appraisal in comp_overall_appraisal_database%}
                                <tr>
                                    <td><a href="{%url 'Appraisals:Detail_PersonalRecord_OverallApp' appraisal.overall_appraisal.id appraisal.id appraisal.employee.id%}">{{appraisal.overall_appraisal.name}}</a></td>
                                <tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div> 







            </div>
        </div>
    </div>
    {%endblock%}
</body>

login2/templates/login2/HuNetAll_UpdateProfile.html
{%extends 'homepage.html'%}
<head>
    <title>{%block title%}User Update{%endblock%}</title>
</head>
<body>
    {%block content%}
    <form action= "" method = "POST">
        {%csrf_token%}
        {{form.as_p}}

        <a class = "btn btn-danger mr-2" type = "button">Cancel</a>
        <input type = 'submit' value = "Update">
    </form>
    {%endblock%}
</body>
</html>

login2/templates/login2/password_change_form.html
{% extends "homepage.html" %}
{% block content %}
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change password</button>
    </form>
{% endblock %}

login2/templates/login2/password_reset.html
<h3>Password Reset</h3>

<p>Forgotten your password?Enter your email address below,and we'll email instructions for setting a new one </p>

<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="Submit" name="send email">
</form>